local exports = {
    -- xcb_window_class_t
    xcb_window_class_t = {
        XCB_WINDOW_CLASS_COPY_FROM_PARENT = 0,
        XCB_WINDOW_CLASS_INPUT_OUTPUT = 1,
        XCB_WINDOW_CLASS_INPUT_ONLY = 2,
    };

    xcb_gc_t = {
        XCB_GC_FUNCTION = 1,
        XCB_GC_PLANE_MASK = 2,
        XCB_GC_FOREGROUND = 4,
        XCB_GC_BACKGROUND = 8,
        XCB_GC_LINE_WIDTH = 16,
        XCB_GC_LINE_STYLE = 32,
        XCB_GC_CAP_STYLE = 64,
        XCB_GC_JOIN_STYLE = 128,
        XCB_GC_FILL_STYLE = 256,
        XCB_GC_FILL_RULE = 512,
        XCB_GC_TILE = 1024,
        XCB_GC_STIPPLE = 2048,
        XCB_GC_TILE_STIPPLE_ORIGIN_X = 4096,
        XCB_GC_TILE_STIPPLE_ORIGIN_Y = 8192,
        XCB_GC_FONT = 16384,
        XCB_GC_SUBWINDOW_MODE = 32768,
        XCB_GC_GRAPHICS_EXPOSURES = 65536,
        XCB_GC_CLIP_ORIGIN_X = 131072,
        XCB_GC_CLIP_ORIGIN_Y = 262144,
        XCB_GC_CLIP_MASK = 524288,
        XCB_GC_DASH_OFFSET = 1048576,
        XCB_GC_DASH_LIST = 2097152,
        XCB_GC_ARC_MODE = 4194304
    };

    xcb_coord_mode_t = {
        XCB_COORD_MODE_ORIGIN = 0,
        XCB_COORD_MODE_PREVIOUS = 1
    };

    xcb_cw_t = {
        XCB_CW_BACK_PIXMAP = 1,
        XCB_CW_BACK_PIXEL = 2,
        XCB_CW_BORDER_PIXMAP = 4,
        XCB_CW_BORDER_PIXEL = 8,
        XCB_CW_BIT_GRAVITY = 16,
        XCB_CW_WIN_GRAVITY = 32,
        XCB_CW_BACKING_STORE = 64,
        XCB_CW_BACKING_PLANES = 128,
        XCB_CW_BACKING_PIXEL = 256,
        XCB_CW_OVERRIDE_REDIRECT = 512,
        XCB_CW_SAVE_UNDER = 1024,
        XCB_CW_EVENT_MASK = 2048,
        XCB_CW_DONT_PROPAGATE = 4096,
        XCB_CW_COLORMAP = 8192,
        XCB_CW_CURSOR = 16384
    };

    xcb_event_mask_t = {
    XCB_EVENT_MASK_NO_EVENT = 0,
    XCB_EVENT_MASK_KEY_PRESS = 1,
    XCB_EVENT_MASK_KEY_RELEASE = 2,
    XCB_EVENT_MASK_BUTTON_PRESS = 4,
    XCB_EVENT_MASK_BUTTON_RELEASE = 8,
    XCB_EVENT_MASK_ENTER_WINDOW = 16,
    XCB_EVENT_MASK_LEAVE_WINDOW = 32,
    XCB_EVENT_MASK_POINTER_MOTION = 64,
    XCB_EVENT_MASK_POINTER_MOTION_HINT = 128,
    XCB_EVENT_MASK_BUTTON_1_MOTION = 256,
    XCB_EVENT_MASK_BUTTON_2_MOTION = 512,
    XCB_EVENT_MASK_BUTTON_3_MOTION = 1024,
    XCB_EVENT_MASK_BUTTON_4_MOTION = 2048,
    XCB_EVENT_MASK_BUTTON_5_MOTION = 4096,
    XCB_EVENT_MASK_BUTTON_MOTION = 8192,
    XCB_EVENT_MASK_KEYMAP_STATE = 16384,
    XCB_EVENT_MASK_EXPOSURE = 32768,
    XCB_EVENT_MASK_VISIBILITY_CHANGE = 65536,
    XCB_EVENT_MASK_STRUCTURE_NOTIFY = 131072,
    XCB_EVENT_MASK_RESIZE_REDIRECT = 262144,
    XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY = 524288,
    XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT = 1048576,
    XCB_EVENT_MASK_FOCUS_CHANGE = 2097152,
    XCB_EVENT_MASK_PROPERTY_CHANGE = 4194304,
    XCB_EVENT_MASK_COLOR_MAP_CHANGE = 8388608,
    XCB_EVENT_MASK_OWNER_GRAB_BUTTON = 16777216
    };


}

return exports
